# conf/train/train.yaml
checkpoint_path: "/home/hk-project-p0024638/usmrd/model_weights/flower_pret/360000_model_weights.pt"
batch_size: 64
steps: 40000
save_freq: 8000
seed: 42
device: cuda
num_workers: 4
log_freq: 100
output_dir: "./output/train/flower/"
job_name: "model_training"
push_to_hub: false
gradient_checkpointing: true
compile_model: false


# Optional: hydra-run specific settings (uncomment to enable overrides)
# hydra:
# run:
# dir: "${output_dir}/hydra_runs"
