repo_id: "your data id"
dataset_path: "your dataset path"
checkpoint_path: /hkfs/work/workspace/scratch/uhtfz-flower/360000_model_weight.pt

train:
  batch_size: 2
  steps: 40000
  save_freq: 100
  seed: 42
  device: cuda
  num_workers: 4
  log_freq: 100
  output_dir: "./output/pi0.5/"
  job_name: "model_training"
  push_to_hub: false
  #Only pi0/pi05
  gradient_checkpointing: true
  compile_model: false

wandb:
  enable: false
  project: "lerobot-training"
  entity: "your-wandb-entity"
  mode: "disabled"  # "online", "offline", "disabled"
