
repo_id: "your_repo_id"
dataset_path: "/hkfs/work/workspace/scratch/uhtfz-flower/vla_data_lerobot"

checkpoint_path: /hkfs/work/workspace/scratch/uhtfz-flower/360000_model_weight.pt
stats_path: /path/to/your/dataset/stats.json # for evaluation
train:
  batch_size: 1
  steps: 60000
  save_freq: 4000
  seed: 42
  device: cuda
  num_workers: 2
  log_freq: 100
  output_dir: "./output/pi05"
  job_name: "model_training"
  push_to_hub: false
  #Only pi0/pi05
  gradient_checkpointing: true
  compile_model: false
  dtype: bfloat16

wandb:
  enable: false
  project: "lerobot-pi0-training"
  entity: "your_wandb_entity"
  mode: "disabled"
