defaults:
  - policy: flower
  - _self_

policy:
  _target_: src.policies.flower.modeling_flower.FlowerVLAPolicy
  repo_id: "flower-finetuned-trickandtreat"
  push_to_hub: false  # Disable automatic push to Hugging Face Hub after training

  action_dim: 8
  chunk_size: 20
  n_obs_steps: 1
  act_window_size: 20
  multistep: 20
  # input_normalization_modes:
  #   observation.state: "min_max"
  # output_normalization_modes:
  #   action: "min_max"

dataset:
  repo_id: "trickandtreat_lerobot"
  root: "/hkfs/work/workspace/scratch/uhtfz-flower/trickandtreat_lerobot"

training:
  batch_size: 64
  steps: 30000
  save_freq: 20000
  log_freq: 100

wandb:
  enable: true
  project: "flower-finetuning"
  entity: j-p-suliga-kit
  mode: "online"  # Change to "offline" to log locally

pretrained_policy_path: "/hkfs/work/workspace/scratch/uhtfz-flower/360000_model_weight.pt"

seed: 42
device: "cuda"
