defaults:
  - policy: flower
  - _self_

policy:
  _target_: src.policies.flower.modeling_flower.FlowerVLAPolicy
  repo_id: "flower-finetuned-trickandtreat"

  action_dim: 8
  chunk_size: 20
  n_obs_steps: 1
  act_window_size: 20
  multistep: 20

dataset:
  repo_id: "trickandtreat_lerobot"
  root: "/home/multimodallearning/data_collected/flower-lerobot/trickandtreat/trickandtreat_lerobot"

training:
  batch_size: 4
  steps: 60
  save_freq: 20000
  log_freq: 100

wandb:
  enable: false
  project: "flower-finetuning"
  entity: null
  mode: "disabled"

pretrained_policy_path: "/home/multimodallearning/Downloads/360000_model_weight.pt"

seed: 42
device: "cuda"
